dist: trusty
sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "8"
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - sh ./install-selenium.sh
  - npm install
  - npm install -g qunit
  - npm install -g eslint

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 60 # give xvfb some time to start

script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - npm test && eslint js/
