dist: trusty
sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "8"
before_install:
  - npm install
  - npm install -g qunit
  - npm install -g eslint

script: npm test && eslint js/
