dist: trusty
sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "8"
before_install:
  - sh ./install-selenium.sh
  - npm install
  - npm install -g qunit
  - npm install -g eslint

before_script:
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start

script:
  - npm test && eslint js/
